# Generated by Django 5.1.4 on 2025-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
