# Generated by Django 5.1.4 on 2026-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_report_evidence_report_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
