# Generated by Django 5.1.4 on 2026-02-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_website_current_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='current_task_id',
        ),
    ]
